### ISSUE TITLE
● Transaction › should be able to import transactions

### ISSUE THREAD

**Issue by diegomrz** [diegomrz/rocketseat-gostack11-desafio06#7]
● Transaction › should be able to import transactions

    expect(received).toHaveLength(expected)

    Expected length: 3
    Received length: 0
    Received array:  []

      220 |     );
      221 | 
    > 222 |     expect(transactions).toHaveLength(3);
          |                          ^
      223 |     expect(transactions).toEqual(
      224 |       expect.arrayContaining([
      225 |         expect.objectContaining({

      at src/__tests__/Transaction.spec.ts:222:26
      at step (src/__tests__/Transaction.spec.ts:33:23)
      at Object.next (src/__tests__/Transaction.spec.ts:14:53)
      at fulfilled (src/__tests__/Transaction.spec.ts:5:58)

**Comment by diegomrz** [comment]
![image](https://user-images.githubusercontent.com/13582313/93163377-61feec00-f6ed-11ea-9543-edbb9423f538.png)
